### ISSUE TITLE
Prefer "@MuonService" rather than "@MuonController"?

### ISSUE THREAD

**Issue by russmiles** [muoncore/muon-java#27]
Since Muon is a microservices-centric library with Spring Boot framework support, would it be better if the annotation for declaring a service be "@MuonService" rather than "@MuonController".

**Comment by daviddawson** [comment]
We have @EnableMuon to switch on the muon functionality.

@MuonController is there to declare that the current class should be inspected for muon related functions (streaming, rpc etc).

I can see these being folded together, so you just annotate @MuonService(name="helloworld")
The other case is for more complex services that require more than one class forming part of the muon interface.  What annotation should there be for that?

Imagine a larger app.

@MuonService(name="hello") class MyMainService {}

@MuonXXX class AnotherPartOfTheInterface {}
^^^^
What should this be called?




/cc @volodymyrpavlenko

**Comment by volodymyrpavlenko** [comment]
When implementing annotations support, I tried to stick to how they are implemented in spring/spring-boot.
We have a direct mapping:
@EnableMuon -> @EnableAutoConfiguration
@MuonController -> @Controller
@MuonRequestListener, @MuonStreamListener -> @RequestListener
@MuonRepository

For a really small service, where we need a single class for controllers, we can introduce a configuration annotation, which would be a 
@MuonSimpleService(name="hello")
and it would inherit @EnableMuon, @MuonController and create the PropertyPlaceholderConfigurer.
